$(info +-------------------------------------------------+)
$(info |                                                 |)
$(info |      Hello, this is Flipper team speaking!      |)
$(info |                                                 |)
$(info |       We've migrated to new build system        |)
$(info |          It's nice and based on scons           |)
$(info |                                                 |)
$(info |      Crash course:                              |)
$(info |                                                 |)
$(info |        `./fbt`                                  |)
$(info |        `./fbt flash`                            |)
$(info |        `./fbt debug`                            |)
$(info |                                                 |)
$(info |      More details in documentation/fbt.md       |)
$(info |                                                 |)
$(info |      Also Please leave your feedback here:      |)
$(info |           https://flipp.dev/4RDu                |)
$(info |                      or                         |)
$(info |           https://flipp.dev/2XM8                |)
$(info |                                                 |)
$(info +-------------------------------------------------+)