Import("env")

env.Append(
    LINT_SOURCES=[
        "#/lib/lfrfid",
    ],
    CPPPATH=[
        "#/lib/lfrfid",
    ],
    SDK_HEADERS=[
        File("#/lib/lfrfid/lfrfid_worker.h"),
        File("#/lib/lfrfid/lfrfid_raw_worker.h"),
        File("#/lib/lfrfid/lfrfid_raw_file.h"),
        File("#/lib/lfrfid/lfrfid_dict_file.h"),
        File("#/lib/lfrfid/tools/bit_lib.h"),
        File("#/lib/lfrfid/protocols/lfrfid_protocols.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="lfrfid")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
