Import("env")

env.Append(
    LINT_SOURCES=[
        Dir("."),
    ],
    CPPPATH=[
        "#/lib/lfrfid",
    ],
    SDK_HEADERS=[
        File("lfrfid_worker.h"),
        File("lfrfid_raw_worker.h"),
        File("lfrfid_raw_file.h"),
        File("lfrfid_dict_file.h"),
        File("protocols/lfrfid_protocols.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="lfrfid")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
