typedef enum {
    HidViewSubmenu,
    HidViewKeynote,
    HidViewKeyboard,
    HidViewNumpad,
    HidViewMedia,
    HidViewMusicMacOs,
    HidViewMovie,
    HidViewMouse,
    HidViewMouseClicker,
    HidViewMouseJiggler,
    HidViewMouseJigglerStealth,
    BtHidViewTikTok,
    HidViewPushToTalk,
    HidViewPushToTalkMenu,
    HidViewPushToTalkHelp,
    HidViewDialog,
    HidViewPopup,
} HidView;
