typedef enum {
    HidViewSubmenu,
    HidViewKeynote,
    HidViewKeyboard,
    HidViewNumpad,
    HidViewMedia,
    HidViewMovie,
    HidViewMouse,
    HidViewMouseClicker,
    HidViewMouseJiggler,
    BtHidViewTikShorts,
    HidViewPushToTalk,
    HidViewPushToTalkMenu,
    HidViewPushToTalkHelp,
} HidView;
