Import("env")

env.Append(
    CPPPATH=[
        "#/lib/infrared/encoder_decoder",
        "#/lib/infrared/worker",
    ],
)


libenv = env.Clone(FW_LIB_NAME="infrared")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
