name: Feature Request
description: For feature requests regarding the firmware.
labels: ['feature request']
body:
- type: markdown
  attributes:
    value: |
      Thank you for taking the time to fill out an issue, this template is meant for any feature suggestions.
      If you require help with the Flipper zero and its firmware, we ask that you join [our forum](https://forum.flipperzero.one)
- type: textarea
  id: proposal
  attributes:
    label: "Description of the feature you're suggesting."
    description: |
      Please describe your feature request in as many details as possible.
        - Describe what it should do.
        - Note whetever it is to extend existing functionality or introduce new functionality.
  validations:
    required: true
- type: textarea
  id: anything-else
  attributes:
    label: Anything else?
    description: Let us know if you have anything else to share.
