Import("env")

env.Append(LINT_SOURCES=["core"])


libenv = env.Clone(FW_LIB_NAME="core")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
