/**
 * @file view_dispatcher_i.h
 * GUI: ViewDispatcher API
 */

#pragma once

#include <m-dict.h>

#include "view_dispatcher.h"
#include "view_i.h"
#include "gui_i.h"

DICT_DEF2(ViewDict, uint32_t, M_DEFAULT_OPLIST, View*, M_PTR_OPLIST) // NOLINT

struct ViewDispatcher {
    bool is_event_loop_owned;
    FuriEventLoop* event_loop;
    FuriMessageQueue* input_queue;
    FuriMessageQueue* event_queue;

    Gui* gui;
    ViewPort* view_port;
    ViewDict_t views;

    View* current_view;

    View* ongoing_input_view;
    uint8_t ongoing_input;

    ViewDispatcherCustomEventCallback custom_event_callback;
    ViewDispatcherNavigationEventCallback navigation_event_callback;
    ViewDispatcherTickEventCallback tick_event_callback;
    uint32_t tick_period;
    void* event_context;
};

/** The Callback that is bound to the ViewPort, called on view_port_draw. Dispatches to the \a current_view.
 *
 * @warning called on the GUI thread.
 *
 * To be used by the GUI, called on tree redraw.
 *
 * @param      canvas     canvas to draw at
 * @param      context    view dispatcher pointer.
 */
void view_dispatcher_draw_callback(Canvas* canvas, void* context);

/** The Callback that is bound to the parent view_port's input. Pushes items into the @a input_queue,
 * to be dispatched via the @a event_loop.
 * \see view_dispatcher_handle_input.
 * \see view_port_input.
 *
 * @param      event      the input event
 * @param      context    view dispatcher pointer.
 */
void view_dispatcher_input_callback(InputEvent* event, void* context);

/** Input handler.
 *
 * @note this will be called on the thread that invoked view_dispatcher_run
 *
 * Events are generated by \a view_port::view_port_input, and relayed through \a event_loop and \a input_queue.
 * \see view_port_input.
 * \see view_dispatcher_handle_input.
 *
 * @param      view_dispatcher    view dispatcher pointer
 * @param      event              the input event
 */
void view_dispatcher_handle_input(ViewDispatcher* view_dispatcher, InputEvent* event);

/** Tick handler
 *
 * @note this will be called on the thread that invoked view_dispatcher_run
 *
 * Events are generated by \a view_port::view_port_input, and relayed through \a event_loop and \a input_queue.
 * \see view_dispatcher_set_tick_event_callback.
 *
 * @param      context    view dispatcher pointer
 */
void view_dispatcher_handle_tick_event(void* context);

/** Custom event handler
 *
 * @note this will be called on the thread that invoked view_dispatcher_run
 *
 * Events are generated by \a view_dispatcher_send_custom_event, and relayed through \a event_loop and \a event_queue.
 * \see view_dispatcher_send_custom_event.
 * \see scene_mananger_handle_custom_event.
 * \see scene_mananger/AppSceneOnEventCallback.
 *
 * @param      view_dispatcher    view dispatcher pointer
 * @param      event              an event id. commonly used with the \em scene_manager, in which case this value is passed into \em on_event_handler
 */
void view_dispatcher_handle_custom_event(ViewDispatcher* view_dispatcher, uint32_t event);

/** Set current view, dispatches view enter and exit */
void view_dispatcher_set_current_view(ViewDispatcher* view_dispatcher, View* view);

/** ViewDispatcher update event */
void view_dispatcher_update(View* view, void* context);

/** ViewDispatcher run event loop event callback */
void view_dispatcher_run_event_callback(FuriEventLoopObject* object, void* context);

/** ViewDispatcher run event loop input callback */
void view_dispatcher_run_input_callback(FuriEventLoopObject* object, void* context);
