Import("env")

env.Append(
    CPPPATH=[
        "#/lib/subghz",
    ],
    SDK_HEADERS=[
        File("subghz/environment.h"),
        File("subghz/receiver.h"),
        File("subghz/subghz_worker.h"),
        File("subghz/subghz_tx_rx_worker.h"),
        File("subghz/transmitter.h"),
        File("subghz/registry.h"),
        File("subghz/protocols/protocol_items.h"),
        File("subghz/protocols/raw.h"),
        File("subghz/blocks/const.h"),
        File("subghz/blocks/decoder.h"),
        File("subghz/blocks/encoder.h"),
        File("subghz/blocks/generic.h"),
        File("subghz/blocks/math.h"),
        File("subghz/subghz_setting.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="subghz")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
