Import("env")

env.Append(
    CPPPATH=[
        "#/lib/ST25RFAL002",
        "#/lib/ST25RFAL002/include",
        "#/lib/ST25RFAL002/source/st25r3916",
    ],
)


libenv = env.Clone(FW_LIB_NAME="st25rfal002")
libenv.ApplyLibFlags()

sources = libenv.GlobRecursive("*.c")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
