Import("env")

env.Append(
    CPPPATH=[
        "#/lib/pulse_reader",
    ],
    SDK_HEADERS=[
        File("pulse_reader.h"),
    ],
)

libenv = env.Clone(FW_LIB_NAME="pulse_reader")
libenv.ApplyLibFlags()

libenv.AppendUnique(
    CCFLAGS=[
        # Required for lib to be linkable with .faps
        "-mword-relocations",
        "-mlong-calls",
    ],
)

sources = libenv.GlobRecursive("*.c*")

lib = libenv.StaticLibrary("${FW_LIB_NAME}", sources)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
