ADD_SCENE(picopass, start, Start)
ADD_SCENE(picopass, read_card, ReadCard)
ADD_SCENE(picopass, read_card_success, ReadCardSuccess)
ADD_SCENE(picopass, card_menu, CardMenu)
ADD_SCENE(picopass, save_name, SaveName)
ADD_SCENE(picopass, save_success, SaveSuccess)
ADD_SCENE(picopass, saved_menu, SavedMenu)
