export function abs(n: number): number;
export function acos(n: number): number;
export function acosh(n: number): number;
export function asin(n: number): number;
export function asinh(n: number): number;
export function atan(n: number): number;
export function atan2(a: number, b: number): number;
export function atanh(n: number): number;
export function cbrt(n: number): number;
export function ceil(n: number): number;
export function clz32(n: number): number;
export function cos(n: number): number;
export function exp(n: number): number;
export function floor(n: number): number;
export function max(n: number, m: number): number;
export function min(n: number, m: number): number;
export function pow(n: number, m: number): number;
export function random(): number;
export function sign(n: number): number;
export function sin(n: number): number;
export function sqrt(n: number): number;
export function trunc(n: number): number;
declare const PI: number;
declare const EPSILON: number;
