ADD_SCENE(namechanger, start, Start)
ADD_SCENE(namechanger, change, Change)
ADD_SCENE(namechanger, change_success, ChangeSuccess)
ADD_SCENE(namechanger, revert, Revert)
ADD_SCENE(namechanger, revert_success, RevertSuccess)
ADD_SCENE(namechanger, error, Error)