/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "application.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_App_StartRequest, PB_App_StartRequest, AUTO)


PB_BIND(PB_App_LockStatusRequest, PB_App_LockStatusRequest, AUTO)


PB_BIND(PB_App_LockStatusResponse, PB_App_LockStatusResponse, AUTO)



