/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "flipper.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_Empty, PB_Empty, AUTO)


PB_BIND(PB_StopSession, PB_StopSession, AUTO)


PB_BIND(PB_Main, PB_Main, AUTO)




