/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.5 */

#include "system.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(PB_System_PingRequest, PB_System_PingRequest, AUTO)


PB_BIND(PB_System_PingResponse, PB_System_PingResponse, AUTO)


PB_BIND(PB_System_RebootRequest, PB_System_RebootRequest, AUTO)


PB_BIND(PB_System_DeviceInfoRequest, PB_System_DeviceInfoRequest, AUTO)


PB_BIND(PB_System_DeviceInfoResponse, PB_System_DeviceInfoResponse, AUTO)




