Import("env")

env.Append(
    LINT_SOURCES=[Dir(".")],
)

libenv = env.Clone(FW_LIB_NAME="flipper${TARGET_HW}")
libenv.Append(
    CPPPATH=[
        "#/lib/STM32CubeWB/Middlewares/ST/STM32_WPAN/interface/patterns/ble_thread/tl",
    ]
)
libenv.ApplyLibFlags()


lib = libenv.StaticLibrary(
    "${FW_LIB_NAME}",
    env.get("TARGET_CFG").gatherSources(),
)
libenv.Install("${LIB_DIST_DIR}", lib)
Return("lib")
