name: Publish the wiki


on:
  push:
    branches: [ master ]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Copy README.md to wiki/Home.md
        run: cp -f README.md wiki/Home.md
      - name: Upload to Wiki
        uses: SwiftDocOrg/github-wiki-publish-action@v1
        with:
          path: "wiki"
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}

