name: Publish the wiki


on:
  push:
    branches: [ master ]


jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v1
      - name: Upload Documentation to Wiki
        run: bash ./.github/deploy_wiki.sh
        env:
          GH_PERSONAL_ACCESS_TOKEN: ${{ secrets.GH_PERSONAL_ACCESS_TOKEN }}
          WIKI_PATH: "wiki"

