name: 'Reindex'

on:
  release:
    types: [prereleased,released]

jobs:
  reindex:
    name: 'Reindex updates'
    runs-on: [self-hosted,FlipperZero]
    steps:
      - name: Trigger reindex
        uses: wei/curl@master
        with:
          args: -X POST -F 'key=${{ secrets.REINDEX_KEY }}' ${{ secrets.REINDEX_URL }}
